import { describe, it, expect } from "vitest";
import { emitIndex } from "../../src/generator/index-emitter.js";

describe("emitIndex", () => {
  it("re-exports the client class by name", () => {
    const output = emitIndex("ApiClient");
    expect(output).toContain(
      "export { ApiClient, ApiError, SESSION_HELP } from './client.js';"
    );
  });

  it("re-exports all types", () => {
    const output = emitIndex("ApiClient");
    expect(output).toContain("export * from './types.js';");
  });

  it("includes auto-generated comment", () => {
    const output = emitIndex("ApiClient");
    expect(output).toContain("// Auto-generated by api-creator");
  });

  it("uses custom client name", () => {
    const output = emitIndex("MyService");
    expect(output).toContain(
      "export { MyService, ApiError, SESSION_HELP } from './client.js';"
    );
  });
});
