import type { AuthInfo } from "../types/auth.js";
import type { Endpoint } from "../types/endpoint.js";
import { methodNameToCliCommand, pathToMethodName } from "../utils/naming.js";

/** Auth type string used in the generated readme authentication section. */
type PrimaryAuthType = "cookie" | "bearer" | "api-key" | undefined;

/**
 * Generates the authentication description line for the README based on detected auth type.
 * @param authType - the primary auth type detected, or undefined if none
 * @returns a single-line description instructing the user how to authenticate
 */
function getAuthDescription(authType: PrimaryAuthType): string {
  if (authType === "cookie") {
    return "This API uses cookie-based authentication. Run:";
  }
  if (authType === "bearer") {
    return "This API uses bearer token authentication. Run:";
  }
  if (authType === "api-key") {
    return "This API uses API key authentication. Run:";
  }
  return "Configure authentication by running:";
}

/**
 * Generates lines listing up to 5 example endpoint commands for the README.
 * @param name - the CLI project name used as the command prefix
 * @param endpoints - the full list of API endpoints
 * @returns array of markdown list-item lines for each example endpoint
 */
function getEndpointExampleLines(
  name: string,
  endpoints: Endpoint[]
): string[] {
  const exampleEndpoints = endpoints.slice(0, 5);
  return exampleEndpoints.map(ep => {
    const methodName = pathToMethodName(ep.method, ep.normalizedPath);
    const cmd = methodNameToCliCommand(methodName, ep.method);
    return `- \`${name} ${cmd}\` -- ${ep.method} ${ep.normalizedPath}`;
  });
}

/**
 * Generates the package.json content for a CLI project.
 * @param name - the CLI project name, used as the package name and binary entry point
 * @returns JSON-formatted package.json string with a trailing newline
 */
export function emitProjectPackageJson(name: string): string {
  const pkg = {
    name,
    version: "0.1.0",
    type: "module",
    bin: {
      [name]: "./bin/cli.js",
    },
    scripts: {
      build: "tsc",
    },
    dependencies: {
      commander: "^14.0.0",
    },
  };
  return `${JSON.stringify(pkg, null, 2)}\n`;
}

/**
 * Generates the tsconfig.json content for a CLI project targeting Node.js ESM.
 * @returns JSON-formatted tsconfig string with a trailing newline
 */
export function emitProjectTsconfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      outDir: "dist",
      rootDir: "src",
      strict: true,
      esModuleInterop: true,
      declaration: true,
      sourceMap: true,
    },
    include: ["src"],
  };
  return `${JSON.stringify(config, null, 2)}\n`;
}

/**
 * Generates the .gitignore content for a CLI project.
 * @returns newline-separated gitignore entries covering build output and auth secrets
 */
export function emitProjectGitignore(): string {
  return ["node_modules", "dist", ".auth", ""].join("\n");
}

/**
 * Generates the shebang bin entry script that invokes the compiled CLI.
 * @param _name - the CLI project name (reserved for future use)
 * @returns the bin/cli.js source lines joined by newlines
 */
export function emitProjectBinEntry(_name: string): string {
  return ["#!/usr/bin/env node", "import '../dist/cli.js';", ""].join("\n");
}

/**
 * Generates a markdown README for the CLI project with setup, auth, and command docs.
 * @param name - the CLI project name
 * @param endpoints - the full list of API endpoints to document
 * @param authInfos - detected auth mechanisms used to tailor the auth section
 * @param originalUrl - the original URL the CLI was generated from
 * @returns the complete README markdown string
 */
export function emitProjectReadme(
  name: string,
  endpoints: Endpoint[],
  authInfos: AuthInfo[],
  originalUrl: string
): string {
  const primaryAuth = authInfos.length > 0 ? authInfos[0] : null;
  const authType = primaryAuth?.type as PrimaryAuthType;
  const overflowCount = endpoints.length - 5;

  return [
    `# ${name}`,
    "",
    `Auto-generated CLI for the API at ${originalUrl}.`,
    "",
    "## Setup",
    "",
    "```bash",
    "npm install",
    "npm run build",
    "```",
    "",
    "## Authentication",
    "",
    getAuthDescription(authType),
    "",
    "```bash",
    `${name} auth setup`,
    "```",
    "",
    "## Commands",
    "",
    ...getEndpointExampleLines(name, endpoints),
    ...(overflowCount > 0 ? [`- ... and ${overflowCount} more`] : []),
    "",
    `Run \`${name} --help\` to see all available commands.`,
    "",
    "---",
    "",
    "Generated by [api-creator](https://github.com/anthropics/api-creator).",
    "",
  ].join("\n");
}
