/**
 * Generate a barrel index.ts that re-exports from client and types modules.
 * @param clientName
 */
export function emitIndex(clientName: string): string {
  const lines: string[] = [];

  lines.push("// Auto-generated by api-creator – do not edit manually");
  lines.push("");
  lines.push(
    `export { ${clientName}, ApiError, SESSION_HELP } from './client.js';`
  );
  lines.push("export * from './types.js';");
  lines.push("");

  return lines.join("\n");
}
