/**
 * Generate a barrel index.ts that re-exports from client and types modules.
 * @param clientName - the exported class name to include in the re-export
 * @returns the complete TypeScript source text for the index barrel file
 */
export function emitIndex(clientName: string): string {
  return [
    "// Auto-generated by api-creator – do not edit manually",
    "",
    `export { ${clientName}, ApiError, SESSION_HELP } from './client.js';`,
    "export * from './types.js';",
    "",
  ].join("\n");
}
