import type { TypeDefinition, PropertyDefinition } from '../parser/type-inferrer.js';

/**
 * Generate TypeScript interface definitions from inferred types.
 */
export function emitTypes(types: TypeDefinition[], requestTypes: TypeDefinition[]): string {
  const allTypes = [...types, ...requestTypes];
  const emitted = new Set<string>();
  const lines: string[] = [];

  lines.push('// Auto-generated by api-creator – do not edit manually');
  lines.push('');

  for (const typeDef of allTypes) {
    emitTypeDefinition(typeDef, lines, emitted);
  }

  return lines.join('\n');
}

function emitTypeDefinition(
  typeDef: TypeDefinition,
  lines: string[],
  emitted: Set<string>,
): void {
  if (emitted.has(typeDef.name)) return;
  emitted.add(typeDef.name);

  // First emit any nested types referenced by properties
  for (const prop of typeDef.properties) {
    if (prop.nestedType && !emitted.has(prop.nestedType.name)) {
      emitTypeDefinition(prop.nestedType, lines, emitted);
    }
  }

  // If the type is an array with no properties, emit it as a type alias
  if (typeDef.isArray && typeDef.properties.length === 0) {
    lines.push(`export type ${typeDef.name} = unknown[];`);
    lines.push('');
    return;
  }

  lines.push(`export interface ${typeDef.name} {`);
  for (const prop of typeDef.properties) {
    const typeStr = formatPropertyType(prop);
    const opt = prop.optional ? '?' : '';
    lines.push(`  ${prop.name}${opt}: ${typeStr};`);
  }
  lines.push('}');
  lines.push('');
}

function formatPropertyType(prop: PropertyDefinition): string {
  const baseType = prop.type;

  if (prop.isArray) {
    // If the type is a union, wrap in parentheses before appending []
    if (baseType.includes(' | ')) {
      return `(${baseType})[]`;
    }
    return `${baseType}[]`;
  }

  return baseType;
}
