import type {
  TypeDefinition,
  PropertyDefinition,
} from "../parser/type-inferrer.js";

/**
 * Formats a property's TypeScript type string, handling arrays and union types.
 * @param prop - the property definition to format
 * @returns the TypeScript type string for the property
 */
function formatPropertyType(prop: PropertyDefinition): string {
  const baseType = prop.type;
  if (prop.isArray) {
    return baseType.includes(" | ") ? `(${baseType})[]` : `${baseType}[]`;
  }
  return baseType;
}

/**
 * Generates source lines for a single type definition, recursively emitting
 * nested types first, and skipping any already-emitted names.
 * @param typeDef - the type definition to emit
 * @param emitted - set of already-emitted type names to prevent duplicates
 * @returns source lines for this type (and any unemitted nested types)
 */
function emitTypeDefinition(
  typeDef: TypeDefinition,
  emitted: ReadonlySet<string>
): { lines: string[]; emitted: ReadonlySet<string> } {
  if (emitted.has(typeDef.name)) return { lines: [], emitted };

  const withSelf = new Set([...emitted, typeDef.name]);

  const { lines: nestedLines, emitted: afterNested } =
    typeDef.properties.reduce<{
      lines: string[];
      emitted: ReadonlySet<string>;
    }>(
      (acc, prop) => {
        if (!prop.nestedType || acc.emitted.has(prop.nestedType.name))
          return acc;
        const result = emitTypeDefinition(prop.nestedType, acc.emitted);
        return {
          lines: [...acc.lines, ...result.lines],
          emitted: result.emitted,
        };
      },
      { lines: [], emitted: withSelf }
    );

  if (typeDef.isArray && typeDef.properties.length === 0) {
    return {
      lines: [...nestedLines, `export type ${typeDef.name} = unknown[];`, ""],
      emitted: afterNested,
    };
  }

  const propLines = typeDef.properties.map(prop => {
    const typeStr = formatPropertyType(prop);
    const opt = prop.optional ? "?" : "";
    return `  ${prop.name}${opt}: ${typeStr};`;
  });

  return {
    lines: [
      ...nestedLines,
      `export interface ${typeDef.name} {`,
      ...propLines,
      "}",
      "",
    ],
    emitted: afterNested,
  };
}

/**
 * Generate TypeScript interface definitions from inferred types.
 * @param types - inferred response type definitions
 * @param requestTypes - inferred request body type definitions
 * @returns the complete TypeScript source text for the types file
 */
export function emitTypes(
  types: TypeDefinition[],
  requestTypes: TypeDefinition[]
): string {
  const allTypes = [...types, ...requestTypes];

  const { lines } = allTypes.reduce<{
    lines: string[];
    emitted: ReadonlySet<string>;
  }>(
    (acc, typeDef) => {
      const result = emitTypeDefinition(typeDef, acc.emitted);
      return {
        lines: [...acc.lines, ...result.lines],
        emitted: result.emitted,
      };
    },
    {
      lines: ["// Auto-generated by api-creator – do not edit manually", ""],
      emitted: new Set(),
    }
  );

  return lines.join("\n");
}
